// Auto-generated by designlang — component anatomy v2.
// Scaffolds. Wire into your token system; not a runtime library.

import * as React from 'react';

export interface CardProps {
  variant?: 'primary';
  size?: 'xl' | 'sm';
  children?: React.ReactNode;
}

export function Card({ variant = 'primary', size = 'md', ...rest }: CardProps) {
  return React.createElement('div', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface ButtonProps {
  variant?: 'outline';
  size?: 'medium' | 'sm';
  leadingIcon?: React.ReactNode;
  children?: React.ReactNode;
}

export function Button({ variant = 'outline', size = 'md', ...rest }: ButtonProps) {
  return React.createElement('button', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface LinkProps {
  variant?: 'primary';
  size?: 'xl';
  children?: React.ReactNode;
}

export function Link({ variant = 'primary', size = 'md', ...rest }: LinkProps) {
  return React.createElement('a', { 'data-variant': variant, 'data-size': size, ...rest });
}
