// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://nuckturp.com.br
// Generated: 2026-05-29T02:29:21.743Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#383838' | '#f7ffe6' | '#beff4d' | '#8c8c8c' | '#000000' | '#1f1f1f' | '#ef4343' | '#8847d1' | '#c08aff' | '#0f0f0f' | '#2e2e2e' | '#f6f6f4' | '#77b30f' | '#ffffff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Space Grotesk';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700' | '900';

export type SpacingToken = '2px' | '96px' | '128px' | '152px' | '192px' | '256px';

export type RadiusToken = '12px' | '16px' | '24px' | '9999px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
